### ISSUE TITLE
drizzle:studio error `Unknown database 'public'`

### ISSUE THREAD

**Issue by ashutoshd11** [w3cj/bytedash#1]
Drizzle studio setup is done seamlessly, but I am getting the error with these pop-ups `Invalid drizzle query` `Unknown database 'public'` on drizzle runner  whereas the same query runs fine on SQL runner
Using drizzle with MySql database.
"drizzle-kit": "^0.20.17",
"drizzle-orm": "^0.30.9",

Need help in resolving this.

**Comment by w3cj** [comment]
I haven't tried with mysql yet, but you will need to make sure everything from this repo is converted over to the mysql specific libraries.

* Schema defined from `drizzle-orm/mysql-core`
* Drizzle connector from `drizzle-orm/mysql2`
* The migrations in this repo are specific to postgres. They would need to be re-generated / replaced for MySQL:
`drizzle-kit generate:mysql`

If your error is not specific to this repo, I recommend asking in the drizzle discord: https://discord.com/invite/yfjTbVXMW4

**Comment by ashutoshd11** [comment]
I checked the above points in my repo, and I am following them correctly. Taking help on discord https://discord.com/channels/1043890932593987624/1043890932593987627/1236997721882366083
